name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Ray
      run: |
        pip install ray[default]

    - name: Install Python dependencies
      run: |
        pip install .
        rm -r gorayffi goray
        pip install -r tests/requirements.txt
    
    - name: Create output directory
      run: |
        mkdir -p output

    - name: Run examples
      run: bash -e examples/basic/run.sh && bash -e examples/crosslang/run.sh
      env:
        RAY_RUNTIME_ENV_IGNORE_GITIGNORE: 1

    - name: Run tests
      run: |
        bash run.sh tests local --py-defs tests/cases/registry.py
        pytest tests/pytests
      env:
        RAY_RUNTIME_ENV_IGNORE_GITIGNORE: 1
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          /tmp/cover.html
          /tmp/cover.out
        retention-days: 30
